force-app/main/default/objects/Feature__c/Feature__c.object-meta.xml
<CustomObject>
    <label>Feature Adoption</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feature Adoptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Feature__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>APIName</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Feature__c/fields/AverageScore__c.field-meta.xml
<CustomField>
    <fullName>AverageScore__c</fullName>
    <label>Average Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FeatureFeedback__c/FeatureFeedback__c.object-meta.xml
<CustomObject>
    <label>Feature Feedback</label>
    <nameField>
        <label>Feature Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feature Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FeatureFeedback__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <label>Feature</label>
    <referenceTo>Feature__c</referenceTo>
    <relationshipLabel>Feature Feedback</relationshipLabel>
    <relationshipName>FeatureFeedback</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FeatureFeedback__c/fields/FeedbackId__c.field-meta.xml
<CustomField>
    <fullName>FeedbackId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Feedback Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FeatureFeedback__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FeatureFeedbackController.cls
public with sharing class FeatureFeedbackController {

    @AuraEnabled
    public static void toggleFeature(String featureName, Boolean active) {
        FeatureManagement.setPackageBooleanValue(featureName, active);
    }

    @AuraEnabled
    public static FeatureInfo getFeatureInfo(String featureName) {
        try {
            // Determine enablement status and any prior feedback score from this user
            List<FeatureFeedback__c> feedbacks = 
                [select Score__c from FeatureFeedback__c 
                    where FeedbackId__c = :buildFeedbackId(featureName)];
            FeatureInfo fi = new FeatureInfo();
            fi.canManage = FeatureManagement.checkPermission('ManageFeatures');
            fi.active = FeatureManagement.checkPackageBooleanValue(featureName);
            fi.userRating = feedbacks.size()==0 ? null : Integer.valueOf(feedbacks[0].Score__c);
            return fi;
        } catch (Exception e) {
            throw new AuraException(e);
        }
    }

    @AuraEnabled
    public static void rateFeature(String featureName, Integer userRating) {
        try {        
            // User rating as Integer (Aura remoting bug)
            userRating = Integer.valueOf(userRating);
            // Record the users rating
            Feature__c featureRecord = new Feature__c();
            featureRecord.APIName__c = featureName;
            featureRecord.Name = featureName;
            upsert featureRecord APIName__c;
            FeatureFeedback__c feedback = new FeatureFeedback__c();
            feedback.Feature__c = featureRecord.Id;
            feedback.FeedbackId__c = buildFeedbackId(featureName);
            feedback.Name = feedback.FeedbackId__c;
            feedback.Score__c = userRating;
            upsert feedback FeedbackId__c;
            // Calculate the new org average for this feature
            AggregateResult[] groupedResults
                = [select AVG(Score__c) score, COUNT(Score__c) scoreCount 
                    from FeatureFeedback__c
                    where Feature__c = :featureRecord.Id];
            if(groupedResults.size()==1) {
                Decimal feedbackAverage = (Decimal) groupedResults[0].get('score');
                Integer feedbackScore = Integer.valueOf(feedbackAverage * 10);
                Integer feedbackCount = Integer.valueOf(groupedResults[0].get('scoreCount'));
                // Update subscriber record
                featureRecord.AverageScore__c = (Decimal) feedbackScore;
                update featureRecord;
                // Send the average user rating back to the LMO, along with the count
                if(feedbackScore!=null && feedbackCount!=null) {
                    updateFeatureManagement(featureName, feedbackCount, feedbackScore);
                }
            }
        } catch (Exception e) {
            throw new AuraException(e);
        }
    }

    /**
     * Perform FeatureManagement calls in async to avoid MIXED_DML_OPERATION errors
     **/
    @future
    public static void updateFeatureManagement(String featureName, Integer count, Integer score) {
        FeatureManagement.setPackageIntegerValue(featureName+'Count', count);
        FeatureManagement.setPackageIntegerValue(featureName+'Score', score);        
    }

    /**
     * Build unique feature feedback Id for this user context and feature
     **/
    private static String buildFeedbackId(String featureName) {
        return featureName + ':' + String.valueOf(UserInfo.getUserId());
    }

    public class FeatureInfo {
        @AuraEnabled
        public Boolean canManage;
        @AuraEnabled
        public Boolean active;
        @AuraEnabled
        public Integer userRating;
    }
}